const API_URL = "http://127.0.0.1:5000/api/";
const API_SIGNUP_URL = API_URL + "sign_up";
const API_SIGNIN_URL = API_URL + "sign_in";

const API_SEARCH_USER_URL = API_URL + "search/user";
const API_GET_PRESET_URL = API_URL + "preset";
const API_SEARCH_ITEM_URL = API_URL + "search/items";
const API_RECOMMEND_ITEM_URL = API_URL + "recommended";
const API_CREATE_MEETING_URL = API_URL + "meeting";
const API_CREATE_WISHLIST_URL = API_URL + "wishlist";
const API_SEARCH_PRODUCT_ID = API_URL + "search/product_id";
const API_UPDATE_WISHLIST_URL = API_URL + "wishlist/update";
const API_CONFIRM_MEETING_URL = API_URL + "confirm";

export {
  API_SIGNIN_URL,
  API_SIGNUP_URL,
  API_SEARCH_USER_URL,
  API_GET_PRESET_URL,
  API_SEARCH_ITEM_URL,
  API_RECOMMEND_ITEM_URL,
  API_CREATE_MEETING_URL,
  API_CREATE_WISHLIST_URL,
  API_SEARCH_PRODUCT_ID,
  API_UPDATE_WISHLIST_URL,
  API_CONFIRM_MEETING_URL,
};
