"""empty message

Revision ID: 92880750c12b
Revises: f3a526f2768a
Create Date: 2020-09-18 03:06:47.905025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92880750c12b'
down_revision = 'f3a526f2768a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_items_product_id', table_name='items')
    op.create_index(op.f('ix_items_product_id'), 'items', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_product_id'), table_name='items')
    op.create_index('ix_items_product_id', 'items', ['product_id'], unique=1)
    # ### end Alembic commands ###
